// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/types/state_data.proto

package iotextypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ProbationCandidateList (slashing #1)
type ProbationCandidateList struct {
	ProbationList        []*ProbationCandidateList_Info `protobuf:"bytes,1,rep,name=probationList,proto3" json:"probationList,omitempty"`
	IntensityRate        uint32                         `protobuf:"varint,2,opt,name=intensityRate,proto3" json:"intensityRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ProbationCandidateList) Reset()         { *m = ProbationCandidateList{} }
func (m *ProbationCandidateList) String() string { return proto.CompactTextString(m) }
func (*ProbationCandidateList) ProtoMessage()    {}
func (*ProbationCandidateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e4d0bfa2d89671, []int{0}
}

func (m *ProbationCandidateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbationCandidateList.Unmarshal(m, b)
}
func (m *ProbationCandidateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbationCandidateList.Marshal(b, m, deterministic)
}
func (m *ProbationCandidateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbationCandidateList.Merge(m, src)
}
func (m *ProbationCandidateList) XXX_Size() int {
	return xxx_messageInfo_ProbationCandidateList.Size(m)
}
func (m *ProbationCandidateList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbationCandidateList.DiscardUnknown(m)
}

var xxx_messageInfo_ProbationCandidateList proto.InternalMessageInfo

func (m *ProbationCandidateList) GetProbationList() []*ProbationCandidateList_Info {
	if m != nil {
		return m.ProbationList
	}
	return nil
}

func (m *ProbationCandidateList) GetIntensityRate() uint32 {
	if m != nil {
		return m.IntensityRate
	}
	return 0
}

type ProbationCandidateList_Info struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbationCandidateList_Info) Reset()         { *m = ProbationCandidateList_Info{} }
func (m *ProbationCandidateList_Info) String() string { return proto.CompactTextString(m) }
func (*ProbationCandidateList_Info) ProtoMessage()    {}
func (*ProbationCandidateList_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e4d0bfa2d89671, []int{0, 0}
}

func (m *ProbationCandidateList_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbationCandidateList_Info.Unmarshal(m, b)
}
func (m *ProbationCandidateList_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbationCandidateList_Info.Marshal(b, m, deterministic)
}
func (m *ProbationCandidateList_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbationCandidateList_Info.Merge(m, src)
}
func (m *ProbationCandidateList_Info) XXX_Size() int {
	return xxx_messageInfo_ProbationCandidateList_Info.Size(m)
}
func (m *ProbationCandidateList_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbationCandidateList_Info.DiscardUnknown(m)
}

var xxx_messageInfo_ProbationCandidateList_Info proto.InternalMessageInfo

func (m *ProbationCandidateList_Info) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ProbationCandidateList_Info) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type VoteBucket struct {
	Index                uint64               `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	CandidateAddress     string               `protobuf:"bytes,2,opt,name=candidateAddress,proto3" json:"candidateAddress,omitempty"`
	StakedAmount         string               `protobuf:"bytes,3,opt,name=stakedAmount,proto3" json:"stakedAmount,omitempty"`
	StakedDuration       uint32               `protobuf:"varint,4,opt,name=stakedDuration,proto3" json:"stakedDuration,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	StakeStartTime       *timestamp.Timestamp `protobuf:"bytes,6,opt,name=stakeStartTime,proto3" json:"stakeStartTime,omitempty"`
	UnstakeStartTime     *timestamp.Timestamp `protobuf:"bytes,7,opt,name=unstakeStartTime,proto3" json:"unstakeStartTime,omitempty"`
	AutoStake            bool                 `protobuf:"varint,8,opt,name=autoStake,proto3" json:"autoStake,omitempty"`
	Owner                string               `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VoteBucket) Reset()         { *m = VoteBucket{} }
func (m *VoteBucket) String() string { return proto.CompactTextString(m) }
func (*VoteBucket) ProtoMessage()    {}
func (*VoteBucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e4d0bfa2d89671, []int{1}
}

func (m *VoteBucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteBucket.Unmarshal(m, b)
}
func (m *VoteBucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteBucket.Marshal(b, m, deterministic)
}
func (m *VoteBucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteBucket.Merge(m, src)
}
func (m *VoteBucket) XXX_Size() int {
	return xxx_messageInfo_VoteBucket.Size(m)
}
func (m *VoteBucket) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteBucket.DiscardUnknown(m)
}

var xxx_messageInfo_VoteBucket proto.InternalMessageInfo

func (m *VoteBucket) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *VoteBucket) GetCandidateAddress() string {
	if m != nil {
		return m.CandidateAddress
	}
	return ""
}

func (m *VoteBucket) GetStakedAmount() string {
	if m != nil {
		return m.StakedAmount
	}
	return ""
}

func (m *VoteBucket) GetStakedDuration() uint32 {
	if m != nil {
		return m.StakedDuration
	}
	return 0
}

func (m *VoteBucket) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *VoteBucket) GetStakeStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StakeStartTime
	}
	return nil
}

func (m *VoteBucket) GetUnstakeStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.UnstakeStartTime
	}
	return nil
}

func (m *VoteBucket) GetAutoStake() bool {
	if m != nil {
		return m.AutoStake
	}
	return false
}

func (m *VoteBucket) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type VoteBucketList struct {
	Buckets              []*VoteBucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VoteBucketList) Reset()         { *m = VoteBucketList{} }
func (m *VoteBucketList) String() string { return proto.CompactTextString(m) }
func (*VoteBucketList) ProtoMessage()    {}
func (*VoteBucketList) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e4d0bfa2d89671, []int{2}
}

func (m *VoteBucketList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteBucketList.Unmarshal(m, b)
}
func (m *VoteBucketList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteBucketList.Marshal(b, m, deterministic)
}
func (m *VoteBucketList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteBucketList.Merge(m, src)
}
func (m *VoteBucketList) XXX_Size() int {
	return xxx_messageInfo_VoteBucketList.Size(m)
}
func (m *VoteBucketList) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteBucketList.DiscardUnknown(m)
}

var xxx_messageInfo_VoteBucketList proto.InternalMessageInfo

func (m *VoteBucketList) GetBuckets() []*VoteBucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type CandidateV2 struct {
	OwnerAddress         string   `protobuf:"bytes,1,opt,name=ownerAddress,proto3" json:"ownerAddress,omitempty"`
	OperatorAddress      string   `protobuf:"bytes,2,opt,name=operatorAddress,proto3" json:"operatorAddress,omitempty"`
	RewardAddress        string   `protobuf:"bytes,3,opt,name=rewardAddress,proto3" json:"rewardAddress,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	TotalWeightedVotes   string   `protobuf:"bytes,5,opt,name=totalWeightedVotes,proto3" json:"totalWeightedVotes,omitempty"`
	SelfStakeBucketIdx   uint64   `protobuf:"varint,6,opt,name=selfStakeBucketIdx,proto3" json:"selfStakeBucketIdx,omitempty"`
	SelfStakingTokens    string   `protobuf:"bytes,7,opt,name=selfStakingTokens,proto3" json:"selfStakingTokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandidateV2) Reset()         { *m = CandidateV2{} }
func (m *CandidateV2) String() string { return proto.CompactTextString(m) }
func (*CandidateV2) ProtoMessage()    {}
func (*CandidateV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e4d0bfa2d89671, []int{3}
}

func (m *CandidateV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateV2.Unmarshal(m, b)
}
func (m *CandidateV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateV2.Marshal(b, m, deterministic)
}
func (m *CandidateV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateV2.Merge(m, src)
}
func (m *CandidateV2) XXX_Size() int {
	return xxx_messageInfo_CandidateV2.Size(m)
}
func (m *CandidateV2) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateV2.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateV2 proto.InternalMessageInfo

func (m *CandidateV2) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *CandidateV2) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *CandidateV2) GetRewardAddress() string {
	if m != nil {
		return m.RewardAddress
	}
	return ""
}

func (m *CandidateV2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CandidateV2) GetTotalWeightedVotes() string {
	if m != nil {
		return m.TotalWeightedVotes
	}
	return ""
}

func (m *CandidateV2) GetSelfStakeBucketIdx() uint64 {
	if m != nil {
		return m.SelfStakeBucketIdx
	}
	return 0
}

func (m *CandidateV2) GetSelfStakingTokens() string {
	if m != nil {
		return m.SelfStakingTokens
	}
	return ""
}

type CandidateListV2 struct {
	Candidates           []*CandidateV2 `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CandidateListV2) Reset()         { *m = CandidateListV2{} }
func (m *CandidateListV2) String() string { return proto.CompactTextString(m) }
func (*CandidateListV2) ProtoMessage()    {}
func (*CandidateListV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e4d0bfa2d89671, []int{4}
}

func (m *CandidateListV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateListV2.Unmarshal(m, b)
}
func (m *CandidateListV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateListV2.Marshal(b, m, deterministic)
}
func (m *CandidateListV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateListV2.Merge(m, src)
}
func (m *CandidateListV2) XXX_Size() int {
	return xxx_messageInfo_CandidateListV2.Size(m)
}
func (m *CandidateListV2) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateListV2.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateListV2 proto.InternalMessageInfo

func (m *CandidateListV2) GetCandidates() []*CandidateV2 {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type VoteBucketsCount struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteBucketsCount) Reset()         { *m = VoteBucketsCount{} }
func (m *VoteBucketsCount) String() string { return proto.CompactTextString(m) }
func (*VoteBucketsCount) ProtoMessage()    {}
func (*VoteBucketsCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e4d0bfa2d89671, []int{5}
}

func (m *VoteBucketsCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteBucketsCount.Unmarshal(m, b)
}
func (m *VoteBucketsCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteBucketsCount.Marshal(b, m, deterministic)
}
func (m *VoteBucketsCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteBucketsCount.Merge(m, src)
}
func (m *VoteBucketsCount) XXX_Size() int {
	return xxx_messageInfo_VoteBucketsCount.Size(m)
}
func (m *VoteBucketsCount) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteBucketsCount.DiscardUnknown(m)
}

var xxx_messageInfo_VoteBucketsCount proto.InternalMessageInfo

func (m *VoteBucketsCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CandidatesCount struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandidatesCount) Reset()         { *m = CandidatesCount{} }
func (m *CandidatesCount) String() string { return proto.CompactTextString(m) }
func (*CandidatesCount) ProtoMessage()    {}
func (*CandidatesCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e4d0bfa2d89671, []int{6}
}

func (m *CandidatesCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidatesCount.Unmarshal(m, b)
}
func (m *CandidatesCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidatesCount.Marshal(b, m, deterministic)
}
func (m *CandidatesCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidatesCount.Merge(m, src)
}
func (m *CandidatesCount) XXX_Size() int {
	return xxx_messageInfo_CandidatesCount.Size(m)
}
func (m *CandidatesCount) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidatesCount.DiscardUnknown(m)
}

var xxx_messageInfo_CandidatesCount proto.InternalMessageInfo

func (m *CandidatesCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*ProbationCandidateList)(nil), "iotextypes.ProbationCandidateList")
	proto.RegisterType((*ProbationCandidateList_Info)(nil), "iotextypes.ProbationCandidateList.Info")
	proto.RegisterType((*VoteBucket)(nil), "iotextypes.VoteBucket")
	proto.RegisterType((*VoteBucketList)(nil), "iotextypes.VoteBucketList")
	proto.RegisterType((*CandidateV2)(nil), "iotextypes.CandidateV2")
	proto.RegisterType((*CandidateListV2)(nil), "iotextypes.CandidateListV2")
	proto.RegisterType((*VoteBucketsCount)(nil), "iotextypes.VoteBucketsCount")
	proto.RegisterType((*CandidatesCount)(nil), "iotextypes.CandidatesCount")
}

func init() { proto.RegisterFile("proto/types/state_data.proto", fileDescriptor_96e4d0bfa2d89671) }

var fileDescriptor_96e4d0bfa2d89671 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x6d, 0x6b, 0xd4, 0x40,
	0x10, 0x26, 0xed, 0xf5, 0xe5, 0xa6, 0xf6, 0xc5, 0x45, 0x6a, 0x28, 0x05, 0x8f, 0x20, 0x36, 0x88,
	0xe6, 0xe4, 0x44, 0x0b, 0x7e, 0xeb, 0x55, 0x84, 0x8a, 0x82, 0x6c, 0x4b, 0x05, 0xbf, 0xc8, 0x5e,
	0x32, 0x4d, 0xd7, 0x5e, 0x76, 0xc3, 0xee, 0x84, 0xb6, 0x7f, 0xc4, 0x3f, 0xe0, 0x6f, 0xf1, 0x7f,
	0x49, 0x36, 0x97, 0x26, 0xb9, 0x1e, 0xf6, 0xdb, 0xcd, 0x33, 0xcf, 0x33, 0x3b, 0x99, 0x67, 0xe6,
	0x60, 0x3f, 0x37, 0x9a, 0xf4, 0x90, 0x6e, 0x73, 0xb4, 0x43, 0x4b, 0x82, 0xf0, 0x67, 0x22, 0x48,
	0x44, 0x0e, 0x66, 0x20, 0x35, 0xe1, 0x8d, 0x4b, 0xee, 0x3d, 0x4b, 0xb5, 0x4e, 0xa7, 0x38, 0x74,
	0x99, 0x49, 0x71, 0x31, 0x24, 0x99, 0xa1, 0x25, 0x91, 0xe5, 0x15, 0x39, 0xf8, 0xeb, 0xc1, 0xee,
	0x37, 0xa3, 0x27, 0x82, 0xa4, 0x56, 0xc7, 0x42, 0x25, 0x32, 0x11, 0x84, 0x5f, 0xa4, 0x25, 0xf6,
	0x15, 0x36, 0xf3, 0x3a, 0x53, 0x02, 0xbe, 0x37, 0x58, 0x0e, 0x37, 0x46, 0x07, 0x51, 0x53, 0x3f,
	0x5a, 0x2c, 0x8d, 0x4e, 0xd4, 0x85, 0xe6, 0x5d, 0x35, 0x7b, 0x0e, 0x9b, 0x52, 0x11, 0x2a, 0x2b,
	0xe9, 0x96, 0x0b, 0x42, 0x7f, 0x69, 0xe0, 0x85, 0x9b, 0xbc, 0x0b, 0xee, 0xbd, 0x87, 0x5e, 0x29,
	0x66, 0x3e, 0xac, 0x89, 0x24, 0x31, 0x68, 0xad, 0xef, 0x0d, 0xbc, 0xb0, 0xcf, 0xeb, 0x90, 0x3d,
	0x81, 0x95, 0x58, 0x17, 0x8a, 0x66, 0xfa, 0x2a, 0x08, 0x7e, 0x2f, 0x03, 0x9c, 0x6b, 0xc2, 0x71,
	0x11, 0x5f, 0x21, 0x95, 0x24, 0xa9, 0x12, 0xbc, 0x71, 0xe2, 0x1e, 0xaf, 0x02, 0xf6, 0x12, 0x76,
	0xe2, 0xba, 0xcf, 0xa3, 0x59, 0xf5, 0x25, 0x57, 0xfd, 0x1e, 0xce, 0x02, 0x78, 0x64, 0x49, 0x5c,
	0x61, 0x72, 0x94, 0xb9, 0xd7, 0x96, 0x1d, 0xaf, 0x83, 0xb1, 0x17, 0xb0, 0x55, 0xc5, 0x1f, 0x0b,
	0xe3, 0x3e, 0xd4, 0xef, 0xb9, 0x9e, 0xe6, 0x50, 0xf6, 0x01, 0x20, 0x36, 0x28, 0x08, 0xcf, 0x64,
	0x86, 0xfe, 0xca, 0xc0, 0x0b, 0x37, 0x46, 0x7b, 0x51, 0x65, 0x4d, 0x54, 0x5b, 0x13, 0x9d, 0xd5,
	0xd6, 0xf0, 0x16, 0x9b, 0x8d, 0x67, 0x6f, 0x9c, 0x92, 0x30, 0xe4, 0xf4, 0xab, 0x0f, 0xea, 0xe7,
	0x14, 0xec, 0x13, 0xec, 0x14, 0x6a, 0xae, 0xca, 0xda, 0x83, 0x55, 0xee, 0x69, 0xd8, 0x3e, 0xf4,
	0x45, 0x41, 0xfa, 0xb4, 0x44, 0xfd, 0xf5, 0x81, 0x17, 0xae, 0xf3, 0x06, 0x28, 0x67, 0xae, 0xaf,
	0x15, 0x1a, 0xbf, 0xef, 0x46, 0x55, 0x05, 0xc1, 0x18, 0xb6, 0x1a, 0x5f, 0xdc, 0x22, 0xbc, 0x81,
	0xb5, 0x89, 0x8b, 0xec, 0x6c, 0xa3, 0x76, 0xdb, 0x1b, 0xd5, 0x90, 0x79, 0x4d, 0x0b, 0xfe, 0x2c,
	0xc1, 0xc6, 0xdd, 0x82, 0x9d, 0x8f, 0x4a, 0x6f, 0x5c, 0xf1, 0xa3, 0xce, 0x86, 0x74, 0x30, 0x16,
	0xc2, 0xb6, 0xce, 0xd1, 0x08, 0xd2, 0xa6, 0x6b, 0xf5, 0x3c, 0x5c, 0x2e, 0xa6, 0xc1, 0x6b, 0x61,
	0x92, 0x9a, 0x57, 0x59, 0xdd, 0x05, 0x19, 0x83, 0x9e, 0x12, 0x19, 0x3a, 0x87, 0xfb, 0xdc, 0xfd,
	0x66, 0x11, 0x30, 0xd2, 0x24, 0xa6, 0xdf, 0x51, 0xa6, 0x97, 0x84, 0x49, 0xd9, 0xbb, 0x75, 0xfe,
	0xf6, 0xf9, 0x82, 0x4c, 0xc9, 0xb7, 0x38, 0xbd, 0x70, 0xe3, 0xaa, 0xbe, 0xf1, 0x24, 0xb9, 0x71,
	0x7e, 0xf6, 0xf8, 0x82, 0x0c, 0x7b, 0x05, 0x8f, 0x6b, 0x54, 0xaa, 0xf4, 0x4c, 0x5f, 0xa1, 0xb2,
	0xce, 0xb8, 0x3e, 0xbf, 0x9f, 0x08, 0x3e, 0xc3, 0x76, 0xe7, 0x0a, 0xcf, 0x47, 0xec, 0x10, 0xe0,
	0x6e, 0xb1, 0xeb, 0x69, 0x3f, 0x6d, 0x4f, 0xbb, 0x35, 0x55, 0xde, 0xa2, 0x06, 0x21, 0xec, 0x34,
	0x46, 0xd8, 0x63, 0xb7, 0xed, 0x77, 0x87, 0x37, 0xbb, 0xa9, 0xea, 0xf0, 0x0e, 0x5a, 0xaf, 0xfe,
	0x8f, 0x38, 0x3e, 0xfc, 0xf1, 0x2e, 0x95, 0x74, 0x59, 0x4c, 0xa2, 0x58, 0x67, 0x43, 0xd7, 0x43,
	0x6e, 0xf4, 0x2f, 0x8c, 0xa9, 0x0a, 0x5e, 0x57, 0x7f, 0x6a, 0xa9, 0x9e, 0x0a, 0x95, 0x0e, 0x9b,
	0x1e, 0x27, 0xab, 0x2e, 0xf1, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xab, 0xae, 0x86,
	0xf6, 0x04, 0x00, 0x00,
}
